[update]
tasks = ["interfaces", "code", "transform", "normalize"]

[update.interfaces]
paths = ["TranslateWebForSafari", "TranslateWebForSafari Extension"]
defaultToBase = true
ignoreEmptyStrings = true
unstripped = false

[update.code]
codePaths = ["TranslateWebForSafari", "TranslateWebForSafari Extension"]
localizablePaths = ["TranslateWebForSafari", "TranslateWebForSafari Extension"]
defaultToKeys = true
additive = true
unstripped = false
plistArguments = true

[update.transform]
codePaths = ["TranslateWebForSafari", "TranslateWebForSafari Extension"]
localizablePaths = ["TranslateWebForSafari", "TranslateWebForSafari Extension"]
transformer = "foundation"
supportedLanguageEnumPath = "."
typeName = "BartyCrouch"
translateMethodName = "translate"

[update.normalize]
paths = ["TranslateWebForSafari", "TranslateWebForSafari Extension"]
sourceLocale = "en"
harmonizeWithSource = true
sortByKeys = true

[lint]
paths = ["TranslateWebForSafari", "TranslateWebForSafari Extension"]
duplicateKeys = true
emptyValues = true
